import type { Timestamp } from "firebase/firestore";

export interface IRestaurant {
  /**
   * ID of the restaurant doc, will be generated by firebase
   */
  id?: string;
  /**
   * Primary store name from google maps
   */
  name: string;
  /**
   * Display name will be used as primary name if provided
   */
  displayName?: string;
  description?: string;
  address: string;
  price?: number;
  /**
   * Star ratings. Used to calculate average rating and show rating given by current user
   */
  stars?: Partial<IStarRating>;
  /**
   * Average rating of the restaurant. Should be read only, and only
   * be modified by the firebase functions on user submit.
   */
  averageStarts?: number;
  /**
   * URL of google maps. Used to navigate to the restaurant on mobile.
   */
  url?: string;
  /**
   * Phone number of the restaurant.
   */
  phoneNumber?: string;
  /**
   * City and state of the restaurant.
   */
  cityAndState?: string;
}

export interface IStarRating {
  1: number;
  2: number;
  3: number;
  4: number;
  5: number;
}

// will be in db named 'restaurant-notes'
export interface INote {
  /**
   * ID of the note doc, will be generated by firebase
   */
  id?: string;
  /**
   * Restaurant id of the restaurant the note is for.
   */
  restaurantId: string;
  /**
   * User id of the user who gave the note.
   */
  userId: string;
  /**
   * Content of the note.
   */
  content: string;
  /**
   * Date the note was created.
   */
  date: Timestamp;
}

export interface IEatQuery {
  /**
   * Does not work since firebase does not support partial string search
   * Name of the restaurant
   */
  name?: string;
  /**
   * City and state of the restaurant
   */
  cityAndState?: string[];
  /**
   * Price range upper bound
   */
  priceRangeUpper?: number;
  /**
   * Price range lower bound
   */
  priceRangeLower?: number;
}

export type TUserRatings = { [restaurantId: string]: number };

export interface ILocationTag {
  value: string;
  count: number;
}
