import type { Timestamp } from "firebase/firestore";

export interface IRestaurant {
  /**
   * ID of the restaurant doc, will be generated by firebase
   */
  id?: string;
  /**
   * Primary store name from google maps
   */
  name: string;
  /**
   * Display name will be used as primary name if provided
   */
  displayName?: string;
  /**
   * Description of the restaurant
   */
  description?: string;
  /**
   * Address of the restaurant, provided by google maps
   */
  address: string;
  /**
   * Price per person
   */
  price?: number;
  /**
   * Star ratings. Used to calculate average rating and show rating given by current user
   */
  stars?: Partial<IStarRating>;
  /**
   * Average rating of the restaurant. Should be read only, and only
   * be modified by the firebase functions on user rating submit.
   * Should be a string to allow for decimal places.
   */
  averageStars?: string;
  /**
   * Not in use
   * Number of ratings of the restaurant. Should be read only, and only
   * be modified by the firebase functions on user rating submit.
   */
  starRatingCount?: number;
  /**
   * URL of google maps. Used to navigate to the restaurant on mobile.
   */
  url?: string;
  /**
   * Phone number of the restaurant.
   */
  phoneNumber?: string;
  /**
   * City and state of the restaurant.
   */
  cityAndState?: string;
  /**
   * Whether the restaurant has a menu.
   * When a user uploads a menu image, gemini API will be used to extract the menu items.
   */
  hasMenu?: boolean;
}

export interface IStarRating {
  1: number;
  2: number;
  3: number;
  4: number;
  5: number;
}

// will be in db named 'restaurant-notes'
export interface INote {
  /**
   * ID of the note doc, will be generated by firebase
   */
  id?: string;
  /**
   * Restaurant id of the restaurant the note is for.
   */
  restaurantId: string;
  /**
   * User id of the user who gave the note.
   */
  userId: string;
  /**
   * Content of the note.
   */
  content: string;
  /**
   * Date the note was created.
   */
  date: Timestamp;
}

export interface IEatQuery {
  /**
   * City and state of the restaurant
   */
  cityAndState?: string[];
  /**
   * Price range upper bound
   */
  priceRangeUpper?: number;
  /**
   * Price range lower bound
   */
  priceRangeLower?: number;
  /**
   * ID of the restaurant
   */
  id?: string;
  /**
   * Name of the restaurant
   */
  name?: string;
}

export type TUserRatings = { [restaurantId: string]: number };

export interface ILocationTag {
  /**
   * Value of the location tag, e.g. "New York, NY"
   */
  value: string;
  /**
   * Count of restaurants with this location tag. This is handled by the firebase functions.
   */
  count: number;
}

/**
 * Payload for menu image upload
 */
export interface IMenuUploadPayload {
  file: File;
  restaurantId: string;
}

export interface IMenu {
  id?: string;
  restaurantId: string;
  categories: {
    [categoryKey: string]: {
      name: {
        en: string;
        zh: string;
      };
      items: IMenuItem[];
    };
  };
  isAYCE: boolean;
  aycePrices?: IAYCEPrice[];
}

export interface IMenuItem {
  name: {
    en: string;
    zh: string;
  };
  /**
   * Price of the menu item, can handle "market price" scenario
   */
  price?: number | string;
  description?: string;
}

export interface IAYCEPrice {
  price: number;
  timePeriod: "Lunch" | "Dinner" | "Weekend" | "Happy Hour" | string;
  additionalInfo?: string;
}
